# Tests generated by Cursor Sonnet 4.5

from fastapi.testclient import TestClient

from main import app


client = TestClient(app)


def test_ping():
    """Test the /ping endpoint returns correct status and response."""
    response = client.get("/ping")
    assert response.status_code == 200
    assert response.json() == {"status": "ok"}


def test_ping_response_structure():
    """Test the /ping endpoint has the correct response structure."""
    response = client.get("/ping")
    data = response.json()
    assert "status" in data
    assert isinstance(data["status"], str)


def test_random():
    """Test the /random endpoint returns a value."""
    response = client.get("/random")
    assert response.status_code == 200
    data = response.json()
    assert "value" in data
    assert data["value"] is not None


def test_random_value_in_range():
    """Test the /random endpoint returns a value between 0 and 100."""
    response = client.get("/random")
    data = response.json()
    value = data["value"]
    assert isinstance(value, int)
    assert 0 <= value <= 100


def test_random_multiple_calls():
    """Test multiple calls to /random endpoint work correctly."""
    for _ in range(10):
        response = client.get("/random")
        assert response.status_code == 200
        value = response.json()["value"]
        assert 0 <= value <= 100


def test_invalid_endpoint():
    """Test that invalid endpoints return 404."""
    response = client.get("/invalid")
    assert response.status_code == 404
