# Tests generated by Cursor Sonnet 4.5

from fastapi.testclient import TestClient

from main import app


client = TestClient(app)


def test_health():
    """Test the /health endpoint returns correct status and response."""
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json() == {"status": "ok"}


def test_health_response_structure():
    """Test the /health endpoint has the correct response structure."""
    response = client.get("/health")
    data = response.json()
    assert "status" in data
    assert isinstance(data["status"], str)


def test_random():
    """Test the /random endpoint returns a value."""
    response = client.get("/random")
    assert response.status_code == 200
    data = response.json()
    assert "value" in data
    assert data["value"] is not None


def test_random_value_in_range():
    """Test the /random endpoint returns a value between 0 and 100."""
    response = client.get("/random")
    data = response.json()
    value = data["value"]
    assert isinstance(value, int)
    assert 0 <= value <= 100


def test_random_multiple_calls():
    """Test multiple calls to /random endpoint work correctly."""
    for _ in range(10):
        response = client.get("/random")
        assert response.status_code == 200
        value = response.json()["value"]
        assert 0 <= value <= 100


def test_port():
    """Test the /port endpoint returns a port number."""
    response = client.get("/port")
    assert response.status_code == 200
    data = response.json()
    assert "port" in data
    assert isinstance(data["port"], int)


def test_port_env_override(monkeypatch):
    """Test /port reflects the PORT env var."""
    monkeypatch.setenv("PORT", "8002")
    response = client.get("/port")
    assert response.json() == {"port": 8002}


def test_invalid_endpoint():
    """Test that invalid endpoints return 404."""
    response = client.get("/invalid")
    assert response.status_code == 404
